USE [master]
GO

/****** Object:  Database [TimeSheetNew]    Script Date: 6/20/2020 10:51:27 AM ******/
CREATE DATABASE [TimeSheetNew]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TimeSheetNew', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TimeSheetNew.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TimeSheetNew_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TimeSheetNew_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TimeSheetNew].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TimeSheetNew] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TimeSheetNew] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TimeSheetNew] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TimeSheetNew] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TimeSheetNew] SET ARITHABORT OFF 
GO

ALTER DATABASE [TimeSheetNew] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [TimeSheetNew] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TimeSheetNew] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TimeSheetNew] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TimeSheetNew] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TimeSheetNew] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TimeSheetNew] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TimeSheetNew] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TimeSheetNew] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TimeSheetNew] SET  ENABLE_BROKER 
GO

ALTER DATABASE [TimeSheetNew] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TimeSheetNew] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TimeSheetNew] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TimeSheetNew] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TimeSheetNew] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TimeSheetNew] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TimeSheetNew] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TimeSheetNew] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TimeSheetNew] SET  MULTI_USER 
GO

ALTER DATABASE [TimeSheetNew] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TimeSheetNew] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TimeSheetNew] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TimeSheetNew] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TimeSheetNew] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TimeSheetNew] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TimeSheetNew] SET  READ_WRITE 
GO


