//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timesheet.Models
{
    using System;
    using System.Collections.Generic;
<<<<<<< HEAD
    
=======
    using System.ComponentModel.DataAnnotations;

>>>>>>> c5ac97e390aff9b7e69a0fd268eff545da2701fe
    public partial class Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor()
        {
            this.Schedules = new HashSet<Schedule>();
        }
<<<<<<< HEAD
    
=======

>>>>>>> c5ac97e390aff9b7e69a0fd268eff545da2701fe
        public Nullable<int> FileNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Sex { get; set; }
        public string Phone { get; set; }
<<<<<<< HEAD
=======
        [Required]
        [DataType(DataType.EmailAddress)]
>>>>>>> c5ac97e390aff9b7e69a0fd268eff545da2701fe
        public string Email { get; set; }
        public int DoctorId { get; set; }
        public int LocationID { get; set; }
        public string Address { get; set; }
<<<<<<< HEAD
    
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedules { get; set; }
=======
        public int GenderID { get; set; }
        public string GenderName { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedules { get; set; }

>>>>>>> c5ac97e390aff9b7e69a0fd268eff545da2701fe
    }
}
