
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Timesheet.Models
{

using System;
    using System.Collections.Generic;
    
public partial class HourCode
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public HourCode()
    {

        this.Schedules = new HashSet<Schedule>();

    }


    public int CodeID { get; set; }

    public string CodeDescription { get; set; }

    public Nullable<decimal> CodeValue { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Schedule> Schedules { get; set; }

}

}
