//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timesheet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int ScheduleID { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> Time_In { get; set; }
        public Nullable<System.DateTime> Time_Out { get; set; }
        public Nullable<int> HourCodeId { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual HourCode HourCode { get; set; }
    }
}
