
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Timesheet.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
{

    public int UserID { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }
    [Required]
    [DataType(DataType.EmailAddress)]
    public string Email { get; set; }

    public string Phone { get; set; }

    public string JobDescription { get; set; }
    [Required]
    [DataType(DataType.Password)]
    public string Password { get; set; }
    public string LoginErrorMessage {get; set;}
    public Nullable<int> JobRoleID { get; set; }



    public virtual Job_Role Job_Role { get; set; }

}

}
